"""empty message

Revision ID: 575f494adba2
Revises: f2192e10de0a
Create Date: 2023-02-27 18:02:22.539391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '575f494adba2'
down_revision = 'f2192e10de0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coffee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.String(length=120), nullable=False))
        batch_op.drop_constraint('coffee_flavor_key', type_='unique')
        batch_op.create_unique_constraint(None, ['size'])
        batch_op.drop_column('flavor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coffee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flavor', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('coffee_flavor_key', ['flavor'])
        batch_op.drop_column('size')

    # ### end Alembic commands ###
